[package]
name = "livrarr-handlers"
version = "0.1.0-alpha6"
edition = "2021"

[dependencies]
livrarr-domain = { workspace = true }
livrarr-http = { path = "../livrarr-http" }
livrarr-matching = { path = "../livrarr-matching" }
axum = { workspace = true, features = ["multipart"] }
tokio = { version = "1", features = ["rt", "macros", "time", "fs"] }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
trait-variant = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
tracing = { workspace = true }
libc = { workspace = true }
data-encoding = "2"
urlencoding = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["fs"] }
image = { workspace = true, features = ["jpeg"] }
reqwest = { workspace = true }
quick-xml = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
