[package]
name = "livrarr-db"
version = "0.1.0-alpha6"
edition = "2021"
license = "GPL-3.0-only"

[features]
test-helpers = []

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
trait-variant = { workspace = true }
livrarr-domain = { workspace = true }
sqlx = { workspace = true }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
