[package]
name = "livrarr-identity"
version = "0.1.0-alpha5"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
livrarr-domain = { workspace = true }
livrarr-external-data = { workspace = true }
livrarr-http = { workspace = true }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
futures = "0.3"
