[package]
name = "livrarr-identity"
version = "0.1.0-alpha6"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
livrarr-domain = { workspace = true }
livrarr-external-data = { workspace = true }
livrarr-http = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
