[package]
name = "livrarr-tagwrite"
version = "0.1.0-alpha5"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tempfile = { workspace = true }
livrarr-domain = { workspace = true }
zip = { workspace = true }
quick-xml = { workspace = true }
repub = { git = "https://github.com/kkodecs/repub", tag = "v0.1.0-alpha" }
mp4ameta = { workspace = true }
id3 = { workspace = true }
