[package]
name = "livrarr-matching"
version = "0.1.0-alpha5"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
livrarr-domain = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
rapidfuzz = { workspace = true }
unicode-normalization = { workspace = true }
id3 = { workspace = true }
rbook = "0.7"
mp4ameta = { workspace = true }
