[package]
name = "livrarr-library"
version = "0.1.0-alpha6"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
thiserror = { workspace = true }
trait-variant = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
livrarr-domain = { workspace = true }
livrarr-db = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
livrarr-db = { workspace = true, features = ["test-helpers"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
