[package]
name = "livrarr-server"
version = "0.1.0-alpha6"
edition = "2021"
license = "GPL-3.0-only"

[[bin]]
name = "livrarr"
path = "src/main.rs"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
trait-variant = { workspace = true }
livrarr-domain = { workspace = true }
livrarr-handlers = { workspace = true }
livrarr-matching = { workspace = true }
livrarr-db = { workspace = true }
livrarr-http = { workspace = true }
livrarr-external-data = { workspace = true }
livrarr-identity = { workspace = true }
livrarr-jobs = { workspace = true }
livrarr-metadata = { workspace = true }
livrarr-download = { workspace = true }
livrarr-library = { workspace = true }
livrarr-tagwrite = { workspace = true }
livrarr-materialize = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "registry"] }
argon2 = { version = "0.5", features = ["std"] }
getrandom = { version = "0.2", features = ["std"] }
hmac = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
axum = { workspace = true, features = ["macros", "multipart"] }
csv = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["fs", "cors", "limit", "trace", "set-header"] }
clap = { version = "4", features = ["derive"] }
tokio-util = { workspace = true }
sqlx = { workspace = true }
urlencoding = { workspace = true }
reqwest = { workspace = true, features = ["multipart", "rustls-tls"] }
image = { workspace = true, features = ["jpeg"] }
lettre = { version = "0.11", default-features = false, features = ["builder", "smtp-transport", "tokio1-rustls-tls", "pool", "hostname", "tracing"] }
uuid = { workspace = true }
tempfile = { workspace = true }
tower_governor = "0.8.0"
dashmap = "6.1.0"
regex = { workspace = true }
data-encoding = "2.10.0"
dhat = { version = "0.3", optional = true }

[features]
dhat-heap = ["dhat"]
test-helpers = ["livrarr-http/test-helpers"]

[dev-dependencies]
livrarr-db = { workspace = true, features = ["test-helpers"] }
livrarr-http = { workspace = true, features = ["test-helpers"] }
